M48
; DRILL file {KiCad (6.0.1-0)} date 2022 February 05, Saturday 10:05:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-05T10:05:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X86.25Y-91.5
X86.25Y-126.0
X167.75Y-91.5
X167.75Y-126.0
T0
M30
